name: 'Changelog generation with git-chglog'
description: 'Generate a changelog using conventional commits using the git-chlog tool'
branding:
  icon: 'calendar'
  color: 'green'

inputs:
  next_version:
    description: 'Next version tag to use instead of UNRELEASED'
    required: false

  config_dir:
    description: 'git-chglog configuration directory'
    default: '.chglog'
    required: true

  filename:
    description: 'Filename to write the changelog to'
    default: 'CHANGELOG.md'
    required: false

  path:
    description: 'Optional path to follow for directory'
    default: ''
    required: false

  tag_query:
    description: 'Optional tag query to use for changelog generation'
    default: ''
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -c
    - ${{ inputs.config_dir }}
    - -n
    - ${{ inputs.next_version }}
    - -o
    - ${{ inputs.filename }}
    - -t
    - ${{ inputs.tag_query }}
    - -p
    - ${{ inputs.path }}
